services:
  - type: web
    name: linalgovistool
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      npm install &&
      npm run build
    startCommand: python start.py
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
